openapi: 3.2.0
info:
  description: All Optilogic users can view the endpoint documentation below, upgrade to a paid account to gain access.
  version: 1.0.0
  title: 'Optilogic REST storage : labels API'
  contact:
    name: Optilogic Support
    email: support@optilogic.com
servers:
- url: https://api.optilogic.app/v0
tags:
- name: 'storage : labels'
  description: Manage custom key/value attributes on a storage record
paths:
  /storage/{storageName}/labels:
    delete:
      tags:
      - 'storage : labels'
      summary: Remove custom key/value pars of labels.
      parameters:
      - name: storageName
        in: path
        required: true
        schema:
          type: string
      - name: labels
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  tags:
                    type: any
                    example:
                      key1: test
                      key2: false
                      key3: 4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - APIKeyHeader: []
      operationId: deleteStorageByStorageNameLabels
      x-operation-id-source: derived
    get:
      tags:
      - 'storage : labels'
      summary: Get labels
      parameters:
      - name: storageName
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  tags:
                    type: any
                    example:
                      key1: test
                      key2: false
                      key3: 4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - APIKeyHeader: []
      operationId: getStorageByStorageNameLabels
      x-operation-id-source: derived
    post:
      tags:
      - 'storage : labels'
      summary: Add labels
      parameters:
      - name: storageName
        in: path
        required: true
        schema:
          type: string
      - name: labels
        in: query
        required: true
        schema:
          type: object
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  tags:
                    type: any
                    example:
                      key1: test
                      key2: false
                      key3: 4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - APIKeyHeader: []
      operationId: postStorageByStorageNameLabels
      x-operation-id-source: derived
    put:
      tags:
      - 'storage : labels'
      summary: Replace labels
      parameters:
      - name: storageName
        in: path
        required: true
        schema:
          type: string
      - name: labels
        in: query
        required: true
        schema:
          type: object
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: success
                  tags:
                    type: any
                    example:
                      key1: test
                      key2: false
                      key3: 4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
      - APIKeyHeader: []
      operationId: putStorageByStorageNameLabels
      x-operation-id-source: derived
components:
  schemas:
    Forbidden:
      type: object
      properties:
        result:
          type: string
          format: string
        error:
          type: string
          format: string
        message:
          type: string
          format: string
        correlationId:
          type: string
          format: uuid
    Error:
      type: object
      properties:
        result:
          type: string
          format: string
        error:
          type: string
          format: string
        correlationId:
          type: string
          format: uuid
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-KEY
externalDocs:
  description: Find out more about Optilogic
  url: https://optilogic.com
